### ISSUE TITLE
ARTIQ corrections

### ISSUE THREAD

**Issue by sbourdeauducq** [nathanshammah/open-quantum-hardware#10]
* ARTIQ also has [dedicated hardware](https://m-labs.hk/experiment-control/sinara-core/) (electronics, no lasers yet sadly) through the Sinara project
* NIST is not the "National Institute for Standard and Time" but the "National Institute of Standards and Technology" 
* Funding and major contributions to the design work were provided by NIST (and still are), but the project has reached beyond NIST.

**Comment by nathanshammah** [comment]
Thanks @sbourdeauducq!
